name: Tests

on: [push,pull_request]



jobs:
  random:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/random
  phpunit:
    needs: random
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/phpunit

  dusk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: PHP version
        run: php -v

      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Make SQLite database
        run: vendor/orchestra/testbench-dusk/create-sqlite-db

      - name: Update Dusk Chromedriver
        run: vendor/bin/dusk-updater detect --auto-update

      - name: Execute Unit Tests
        run: vendor/bin/phpunit --testsuite=Browser

      - name: Upload Failed Screenshots
        uses: actions/upload-artifact@v2-preview
        if: failure()
        with:
          name: screenshots
          path: tests/Browser/screenshots/*
